In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('files/1/fifa.csv')

In [3]:
data.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [6]:
pd.set_option('display.max_rows', 164)
data['Nationality'].value_counts()

England                 1662
Germany                 1198
Spain                   1072
Argentina                937
France                   914
Brazil                   827
Italy                    702
Colombia                 618
Japan                    478
Netherlands              453
Sweden                   397
China PR                 392
Chile                    391
Republic of Ireland      368
Mexico                   366
United States            353
Poland                   350
Norway                   341
Saudi Arabia             340
Denmark                  336
Korea Republic           335
Portugal                 322
Turkey                   303
Austria                  298
Scotland                 286
Belgium                  260
Australia                236
Switzerland              220
Uruguay                  149
Senegal                  130
Wales                    129
Serbia                   126
Croatia                  126
Nigeria                  121
Ghana                    114
Greece                   102
Ivory Coast              100
Czech Republic           100
Cameroon                  90
Paraguay                  85
Morocco                   85
Northern Ireland          80
Russia                    79
Ukraine                   73
South Africa              71
Finland                   67
Venezuela                 67
Canada                    64
Bosnia Herzegovina        61
Algeria                   60
Slovenia                  55
Romania                   54
Slovakia                  54
DR Congo                  52
Iceland                   47
New Zealand               44
Mali                      43
Ecuador                   43
Albania                   40
Hungary                   38
Peru                      37
Kosovo                    33
Jamaica                   32
Bulgaria                  32
Tunisia                   32
Egypt                     31
Guinea                    31
Bolivia                   30
Costa Rica                30
India                     30
Georgia                   26
Congo                     25
Montenegro                23
FYR Macedonia             20
Cape Verde                19
Iran                      17
Burkina Faso              16
Honduras                  16
Gambia                    15
Gabon                     15
Benin                     15
Guinea Bissau             15
Panama                    15
Angola                    15
Curacao                   14
Israel                    14
Estonia                   13
Zimbabwe                  13
Madagascar                12
Togo                      12
Kenya                     10
Haiti                     10
Armenia                   10
Zambia                     9
Syria                      9
Lithuania                  8
Luxembourg                 8
Cyprus                     8
Iraq                       7
Uganda                     6
Sierra Leone               6
Comoros                    6
Latvia                     6
Faroe Islands              6
Moldova                    5
Equatorial Guinea          5
Thailand                   5
El Salvador                5
Azerbaijan                 5
Afghanistan                4
Korea DPR                  4
Montserrat                 4
Mozambique                 4
Suriname                   4
Mauritania                 4
Libya                      4
Antigua & Barbuda          4
Cuba                       4
Belarus                    4
Trinidad & Tobago          4
Kazakhstan                 4
Niger                      3
Burundi                    3
St Kitts Nevis             3
Liechtenstein              3
Sudan                      3
Namibia                    3
Central African Rep.       3
Guyana                     3
Tanzania                   3
Barbados                   3
Guatemala                  3
Nicaragua                  2
Philippines                2
Hong Kong                  2
Bermuda                    2
Eritrea                    2
Chad                       2
Uzbekistan                 2
Dominican Republic         2
Andorra                    1
Malta                      1
Belize                     1
Qatar                      1
South Sudan                1
Puerto Rico                1
Rwanda                     1
Jordan                     1
Indonesia                  1
Grenada                    1
Oman                       1
Ethiopia                   1
St Lucia                   1
Palestine                  1
Lebanon                    1
Guam                       1
Liberia                    1
Mauritius                  1
Kuwait                     1
New Caledonia              1
Fiji                       1
São Tomé & Príncipe        1
United Arab Emirates       1
Botswana                   1
Name: Nationality, dtype: int64

In [10]:
def decompose_categorical(x):
    if x == 'England':
        return 'England'
    if x == 'Germany':
        return 'Germany'
    if x == 'Spain':
        return 'Spain'
    if x == 'Argentina':
        return 'Argentina'
    if x == 'France':
        return 'France'
    
    return 'Others'
        
data['Nationality'] = data['Nationality'].apply(decompose_categorical)
data['Nationality'].value_counts()

Others       12424
England       1662
Germany       1198
Spain         1072
Argentina      937
France         914
Name: Nationality, dtype: int64